### ISSUE TITLE
I get: Class MCFileWriterUtil was not exported. Did you forget to use RCT_EXPORT_MODULE()

### ISSUE THREAD

**Issue by yayolius** [ModusCreateOrg/custom-react-native-components-part1#1]
Hello, i am having problem getting to work your Tutorial from  an empty project  created from the "react-native init CustomComponent" command.
I follow all your examples and Guides for Phase 1, but when i try to run the project i get that error in the emulator. The problem does not occur when i clone this repository the project works without issues.

Can you help me?
Thanks
Claudio

**Comment by jaygarcia** [comment]
Hi Claudio,

What's the error that you're getting?  Can you 1) share the repo or 2) post photos or text of the exception(s)?

**Comment by yayolius** [comment]
Hi Jay it seems that the problem is that the guys from [react-native] just changed the way that you declare the NativeComponents as someone replied me in here

http://stackoverflow.com/questions/29552377/how-to-implement-native-module-in-react-native/29557740#29557740

The reason that the one that you have online works is probably because it uses an "older" version of react-native.
Thanks

**Comment by jaygarcia** [comment]
Hi Claudio,

Yes. That's absolutely correct. I updated the article & the repo this morning and forgot to reply.

**Comment by yayolius** [comment]
This is maybe an unrelated issue maybe but when i pack my repository in
git, upload and then clone it, i get a weird

../react-native-font-list/iOS/NativeFonts.h:9:9: 'RCTBridgeModule.h' file
not found

The repository is:
https://github.com/yayolius/react-native-font-list/tree/master

Can you help me please?
Thanks

2015-04-10 15:29 GMT-03:00 Jay Garcia <notifications@github.com>:

**Comment by jaygarcia** [comment]
Dude, this demo is awesome! =)

The fix to your instructions:
- cd <project_dir>
- npm install
- run Xcode project 


Works like a champ for me =)

Fantastic wor

**Comment by ecris87** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
