### ISSUE TITLE
custom components for android tutorial?

### ISSUE THREAD

**Issue by waleedarshad-vf** [ModusCreateOrg/custom-react-native-components-part1#3]

**Comment by ecris87** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
